FROM debian:9.7-slim
# apt-key requires gnupg https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869873
# we're using gnupg for encryption as well, so that makes sense...
RUN apt-get update && \
    apt-get install -y gnupg curl
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 && \
    echo "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list && \
    apt-get update && \
    apt-get install -y mongodb-org-tools=4.0.0 s3cmd && \
    apt-get clean
WORKDIR /scripts
COPY backup.sh ./
VOLUME /backups
ENTRYPOINT [ "/bin/sh", "./backup.sh" ]
