FROM debian:10-slim
# mongodb tools currently officially supports Debian 8, 9, 10 -- weird,
# given that 10 is "oldstable" and 8 officially obsolete as of Jan '22
# NOTE: Don't use the debian standard package "mogon-tools", they are very, very outdated!
# ---
RUN apt-get update && \
    apt-get install -y gnupg curl s4cmd && \
    curl https://fastdl.mongodb.org/tools/db/mongodb-database-tools-debian10-x86_64-100.5.1.deb --output mongo-tools.deb && \
    apt install ./mongo-tools.deb && \
    apt-get clean
WORKDIR /scripts
COPY backup.sh ./
VOLUME /backups
ENTRYPOINT [ "/bin/sh", "./backup.sh" ]
