{{- if .Values.gpg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cmmdbb.fullname" . }}-encryption-pk
  labels:
    app: {{ template "cmmdbb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  gpg.pub: {{ .Values.gpg.publicKey }}
{{- end }}
